/*!
 * voip.h
 *
 * Copyright 2007 Severin LAGEDER <severin.Lageder@efixo.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * $Id: voip.h 17878 2010-10-01 07:23:02Z mgo $
 */

#ifndef _PLUGIN_VOIP_H_
#define _PLUGIN_VOIP_H_

#include "query.h"

#ifndef PSTN_LIFE_LINE_SUPPORT
#ifdef NB4
#define PSTN_LIFE_LINE_SUPPORT 1
#else
#define PSTN_LIFE_LINE_SUPPORT 0
#endif
#endif

struct nbd_phone_call_t {
	unsigned short type;	/* NBD_PHONE_CALL_PSTN or NBD_PHONE_CALL_VOIP */
	unsigned short direction;	/* NBD_PHONE_CALL_INCOMING or NBD_PHONE_CALL_OUTGOING */
	char number[32];	/* phone number of the interlocutor */
	int length;		/* length of the call (in seconds) */
	time_t date;		/* date of the call */
};

struct plugin;

extern struct plugin voip_plugin;

int reg_init(void);
void voip_update_leds(void);

/* Lageder 19.10.2006 : Audio control
 * enum for life CLI - audio interaction commands
 * TAKE CARE: this structure has to be identical to
 * the one discribed in endpt.h
 * xChange/dslx_common/voice_res_gw/endpt/inc/endpt.h !!
 */

/* About what follows: */
/* LAGEDER 16.11.2007: WARNING! This is excerpt of some headers of
 * broadcoms endpoint driver. Quite ugly, but there are too many
 * header dependency & incompatibility issues
 * concerned files are: endpt.h
 *                 endpointdrv.h
 */

typedef enum {
	//Jitter Buffer                                             //0
	VAR_SET_JITTER_ALGO,
	VAR_GET_JITTER_ALGO,
	VAR_SET_JITTER_VOICE_MIN,
	VAR_GET_JITTER_VOICE_MIN,
	VAR_SET_JITTER_VOICE_MAX,
	VAR_GET_JITTER_VOICE_MAX,	//5
	VAR_SET_JITTER_VOICE_TARGET,
	VAR_GET_JITTER_VOICE_TARGET,
	VAR_SET_JITTER_DATA_TARGET,
	VAR_GET_JITTER_DATA_TARGET,

	//Gain
	VAR_SET_INGRESS_GAIN,	//10
	VAR_GET_INGRESS_GAIN,
	VAR_SET_EGRESS_GAIN,
	VAR_GET_EGRESS_GAIN,

	//Echo cancellator vars
	//VOLUME (egress) COMPRESSOR
	VAR_SET_VOLCOMPRESSOR_PEAK,
	VAR_SET_VOLCOMPRESSOR_BACKGRD_NOISE_SUPPRESS,	//15
	VAR_SET_VOLCOMPRESSOR_AGC_TARGET,
	VAR_SET_VOLCOMPRESSOR_AGC_ATTACK,
	VAR_SET_VOLCOMPRESSOR_AGC_DECAY,
	//GAIN (ingress) COMPRESSOR
	VAR_SET_GCOMPRESSOR_PEAK,
	VAR_SET_GCOMPRESSOR_BACKGRD_NOISE_SUPPRESS,	//20
	VAR_SET_GCOMPRESSOR_AGC_TARGET,
	VAR_SET_GCOMPRESSOR_AGC_ATTACK,
	VAR_SET_GCOMPRESSOR_AGC_DECAY,

	//ERL REGS
	VAR_SET_ERL_MIN,
	VAR_SET_ERL_MAX,	//25

	//Echo cancellator cmds
	CMD_NLP,
	CMD_ADAPT,
	CMD_BYPASS,
	CMD_LOOPBACK,
	CMD_PUSH,		//30
	CMD_MUTE,
	CMD_SWITCH_LEV_CTL,
	CMD_ALL,

	//Add-ons:
	CMD_DUMP_SLIC_REGS,
	CMD_DUMP_DAA_REGS,
	//Slic Register set command
	VAR_SET_SLIC_IR13_RX,
	VAR_SET_SLIC_IR14_TX,
	VAR_SET_SLIC_DR9,

	//Lageder insert 12.11.2007
	//Read back Slic & Daa regs to userspace
	VAR_GET_SLIC_REG,
	VAR_GET_DAA_REG,

	//slr insert 13.01.2009
	//write slic and daa registers from userspace. DANGEROUS FEATURE!
	VAR_SET_SLIC_REG,
	VAR_SET_DAA_REG
} CLIAUDIOCMD;

typedef enum ENDPOINTIOCTL_INDEX {
	ENDPTIO_INIT_INDEX = 0,
	ENDPTIO_DEINIT_INDEX,
	ENDPTIO_CREATE_INDEX,
	ENDPTIO_DESTROY_INDEX,
	ENDPTIO_CAPABILITIES_INDEX,
	ENDPTIO_SIGNAL_INDEX,
	ENDPTIO_CREATE_CONNECTION_INDEX,
	ENDPTIO_MODIFY_CONNECTION_INDEX,
	ENDPTIO_DELETE_CONNECTION_INDEX,
	ENDPTIO_MUTE_CONNECTION_INDEX,
	ENDPTIO_PACKET_INDEX,
	ENDPTIO_GET_PACKET_INDEX,
	ENDPTIO_GET_EVENT_INDEX,
	ENDPTIO_GET_CODECMAP_INDEX,
	ENDPTIO_VOICESTAT_INDEX,
	ENDPTIO_ISINITIALIZED_INDEX,
	ENDPTIO_CONSOLE_CMD_INDEX,
	ENDPTIO_TEST_INDEX,
	ENDPTIO_ENDPOINTCOUNT_INDEX,
#ifdef NTR_SUPPORT
	ENDPTIO_NTR_CMD_INDEX,
#endif /* NTR_SUPPORT */
#if PSTN_LIFE_LINE_SUPPORT
	ENDPTIO_HOOKSTAT_INDEX,
	ENDPTIO_SET_RELAY_INDEX,
#endif
	ENDPTIO_PRINTF_INDEX,
#if PSTN_LIFE_LINE_SUPPORT
//Lageder 13.07.2006 "999" escape code handling | + others
	ENDPTIO_GET_DAA_HOOKSTATE_INDEX,
#endif
	ENDPTIO_SET_JITTER_VALS_INDEX,
	ENDPTIO_HEC_INTERACT_INDEX,
	ENDPTIO_GAIN_INTERACT_INDEX,
	ENDPTIO_AUDIO_INTERACT_INDEX,
#ifdef EFIXO_PCM_DEBUG
	ENDPTIO_DUMP_PCM_REGS_INDEX,
#endif /* EFIXO_PCM_DEBUG */
	//---------------------------
	ENDPTIO_MAX_INDEX
} ENDPOINTIOCTL_INDEX;

/* Defines. */
#define ENDPOINTDRV_MAJOR            209	/* arbitrary unused value */

/* LAGEDER 16.11.2007: WARNING! A copy of those exists in the header
 * of the voip plugin of neufbox-daemon because of many header dependency &
 * incompatibility issues */

#define ENDPOINTIOCTL_ENDPT_INIT \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_INIT_INDEX, ENDPOINTDRV_INIT_PARAM)

#define ENDPOINTIOCTL_ENDPT_DEINIT \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_DEINIT_INDEX, ENDPOINTDRV_INIT_PARAM)

#define ENDPOINTIOCTL_ENDPT_CREATE \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_CREATE_INDEX, ENDPOINTDRV_CREATE_PARM)

#define ENDPOINTIOCTL_ENDPT_DESTROY \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_DESTROY_INDEX, ENDPOINTDRV_DESTROY_PARM)

#define ENDPOINTIOCTL_ENDPT_CAPABILITIES \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_CAPABILITIES_INDEX, ENDPOINTDRV_CAP_PARM)

#define ENDPOINTIOCTL_ENDPT_SIGNAL \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_SIGNAL_INDEX, ENDPOINTDRV_SIGNAL_PARM)

#define ENDPOINTIOCTL_ENDPT_CREATE_CONNECTION \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_CREATE_CONNECTION_INDEX, ENDPOINTDRV_CONNECTION_PARM)

#define ENDPOINTIOCTL_ENDPT_MODIFY_CONNECTION \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_MODIFY_CONNECTION_INDEX, ENDPOINTDRV_CONNECTION_PARM)

#define ENDPOINTIOCTL_ENDPT_DELETE_CONNECTION \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_DELETE_CONNECTION_INDEX, ENDPOINTDRV_DELCONNECTION_PARM)

#define ENDPOINTIOCTL_ENDPT_MUTE_CONNECTION \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_MUTE_CONNECTION_INDEX, ENDPOINTDRV_MUTECONNECTION_PARM)

#define ENDPOINTIOCTL_ENDPT_PACKET \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_PACKET_INDEX, ENDPOINTDRV_PACKET_PARM)

#define ENDPOINTIOCTL_ENDPT_GET_PACKET \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_GET_PACKET_INDEX, ENDPOINTDRV_PACKET_PARM)

#define ENDPOINTIOCTL_ENDPT_GET_EVENT \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_GET_EVENT_INDEX, ENDPOINTDRV_EVENT_PARM)

#define ENDPOINTIOCTL_ENDPT_GET_CODECMAP \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_GET_CODECMAP_INDEX, ENDPOINTDRV_CODECMAP_PARM)

#define ENDPOINTIOCTL_ENDPT_VOICESTAT \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_VOICESTAT_INDEX, ENDPOINTDRV_VOICESTAT_PARM)

#define ENDPOINTIOCTL_ISINITIALIZED \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_ISINITIALIZED_INDEX, ENDPOINTDRV_ISINITIALIZED_PARM)

#define ENDPOINTIOCTL_ENDPT_CONSOLE_CMD \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_CONSOLE_CMD_INDEX, ENDPOINTDRV_CONSOLE_CMD_PARM)

#define ENDPOINTIOCTL_TEST \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_TEST_INDEX, ENDPOINTDRV_TESTPARM)

#define ENDPOINTIOCTL_ENDPOINTCOUNT \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_ENDPOINTCOUNT_INDEX, ENDPOINTDRV_ENDPOINTCOUNT_PARM)

#ifdef NTR_SUPPORT
#define ENDPTIO_NTR_CMD \
		    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_NTR_CMD_INDEX, ENDPOINTDRV_NTR_PARM)
#endif /* NTR_SUPPORT */

#if PSTN_LIFE_LINE_SUPPORT
#define ENDPOINTIOCTL_HOOKSTAT \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_HOOKSTAT_INDEX, ENDPOINTDRV_HOOKSTAT_CMD_PARM)

#define ENDPOINTIOCTL_SET_RELAY \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_SET_RELAY_INDEX, ENDPOINTDRV_RELAY_CMD_PARM)
#endif

#define ENDPOINTIOCTL_PRINTF \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_PRINTF_INDEX, ENDPOINTDRV_PRINTF_PARM)

#if PSTN_LIFE_LINE_SUPPORT
//Lageder 13.07.2006 "999" escape code
#define ENDPOINTIOCTL_ENDPOINT_DAA_HOOKSTATE \
    _IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_GET_DAA_HOOKSTATE_INDEX, ENDPOINTDRV_DAA_HOOKSTATE_PARM)
//-----------------
#endif

//Lageder 09.10.2006 insert: set Jitter buffer values manually
#define ENDPTIOCTL_SET_JITTER_VALS \
	_IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_SET_JITTER_VALS_INDEX, ENDPOINTDRV_JITTERBUFFER_PARM)
//---------------------

//Lageder 0.10.2006 insert: interact with HEC registers
#define ENDPTIOCTL_HEC_INTERACT \
	_IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_HEC_INTERACT_INDEX, ENDPOINTDRV_JITTERBUFFER_PARM)
//---------------------

//Lageder 0.10.2006 insert: set Gain values manually
#define ENDPTIOCTL_GAIN_INTERACT \
	_IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_GAIN_INTERACT_INDEX, ENDPOINTDRV_GAIN_PARM)
//---------------------

//Lageder 19.10.2006 insert: interact with DSP
#define ENDPTIOCTL_AUDIO_INTERACT \
	_IOWR(ENDPOINTDRV_MAJOR, ENDPTIO_AUDIO_INTERACT_INDEX, ENDPOINTDRV_AUDIO_PARM)

#ifdef EFIXO_PCM_DEBUG
//Tanguy 17.08.2009 dump live pcm registers
#define ENDPTIOCTL_DUMP_PCM_REGS \
	_IO(ENDPOINTDRV_MAJOR, ENDPTIO_DUMP_PCM_REGS_INDEX)
#endif /* EFIXO_PCM_DEBUG */

#define MAX_ENDPOINTDRV_IOCTL_COMMANDS   ENDPTIO_MAX_INDEX

//Lageder 19.10.2006 insert: HW interaction CMDs
typedef struct {
	unsigned int size;
	CLIAUDIOCMD command;
	int argument1;
	int argument2;
} ENDPOINTDRV_AUDIO_PARM, *PENDPOINTDRV_AUDIO_PARM;

#ifdef NB6

#define SI32176_VCM_RING_FIXED		482
#define SI32176_DELTA_VCM			483
#define SI32176_DCDC_FSW_VTHLO		489
#define SI32176_DCDC_FSW_VHYST		490
#define SI32176_TXACIIR_B0_1		518
#define SI32176_TXACIIR_B1_1		519
#define SI32176_TXACIIR_A1_1		520
#define SI32176_TXACIIR_B0_2		521
#define SI32176_TXACIIR_B1_2		522
#define SI32176_TXACIIR_B2_2		523
#define SI32176_TXACIIR_A1_2		524
#define SI32176_TXACIIR_A2_2		525
#define SI32176_TXACIIR_B0_3		526
#define SI32176_TXACIIR_B1_3		527
#define SI32176_TXACIIR_B2_3		528
#define SI32176_TXACIIR_A1_3		529
#define SI32176_TXACIIR_A2_3		530
#define SI32176_TXACHPF_A1_1		533
#define SI32176_TXACEQ_C0			540
#define SI32176_TXACEQ_C1			541
#define SI32176_TXACEQ_C2			542
#define SI32176_TXACEQ_C3			543
#define SI32176_TXACGAIN			544
#define SI32176_RXACGAIN			545
#define SI32176_RXACEQ_C0			546
#define SI32176_RXACEQ_C1			547
#define SI32176_RXACEQ_C2			548
#define SI32176_RXACEQ_C3			549
#define SI32176_RXACIIR_B0_1		550
#define SI32176_RXACIIR_B1_1		551
#define SI32176_RXACIIR_A1_1		552
#define SI32176_RXACIIR_B0_2		553
#define SI32176_RXACIIR_B1_2		554
#define SI32176_RXACIIR_B2_2		555
#define SI32176_RXACIIR_A1_2		556
#define SI32176_RXACIIR_A2_2		557
#define SI32176_RXACIIR_B0_3		558
#define SI32176_RXACIIR_B1_3		559
#define SI32176_RXACIIR_B2_3		560
#define SI32176_RXACIIR_A1_3		561
#define SI32176_RXACIIR_A2_3		562
#define SI32176_ECFIR_C2			563
#define SI32176_ECFIR_C3			564
#define SI32176_ECFIR_C4			565
#define SI32176_ECFIR_C5			566
#define SI32176_ECFIR_C6			567
#define SI32176_ECFIR_C7			568
#define SI32176_ECFIR_C8			569
#define SI32176_ECFIR_C9			570
#define SI32176_ECIIR_B0			571
#define SI32176_ECIIR_B1			572
#define SI32176_ECIIR_A1			573
#define SI32176_ECIIR_A2			574
#define SI32176_SLOPE_VLIM			634
#define SI32176_SLOPE_RFEED			635
#define SI32176_SLOPE_ILIM			636
#define SI32176_SLOPE_RING			637
#define SI32176_SLOPE_DELTA1		638
#define SI32176_SLOPE_DELTA2		639
#define SI32176_V_VLIM				640
#define SI32176_V_RFEED				641
#define SI32176_V_ILIM				642
#define SI32176_CONST_RFEED			643
#define SI32176_CONST_ILIM			644
#define SI32176_I_VLIM				645
#define SI32176_ZSYNTH_B0			653
#define SI32176_ZSYNTH_B1			654
#define SI32176_ZSYNTH_B2			655
#define SI32176_ZSYNTH_A1			656
#define SI32176_ZSYNTH_A2			657
#define SI32176_RXACHPF_B0_1		658
#define SI32176_RXACHPF_B1_1		659
#define SI32176_RXACHPF_A1_1		660
#define SI32176_LCRDBI				701
#define SI32176_LONGDBI				702
#define SI32176_VCM_OH				748
#define SI32176_VCM_RING			749
#define SI32176_VOV_GND				751
#define SI32176_VOV_BAT				752
#define SI32176_VOV_RING_BAT		753
#define SI32176_RTPER				755
#define SI32176_P_TH_HVIC			756
#define SI32176_COEF_P_HVIC			759
#define SI32176_VBATH_EXPECT		767
#define SI32176_VBATR_EXPECT		768
#define SI32176_UNUSED783			783
#define SI32176_RINGOF				843
#define SI32176_RINGFR				844
#define SI32176_RINGAMP				845
#define SI32176_RINGPHAS			846
#define SI32176_RTDCTH				847
#define SI32176_RTACTH				848
#define SI32176_RTDCDB				849
#define SI32176_RTACDB				850
#define SI32176_LCROFFHK			852
#define SI32176_LCRONHK				853
#define SI32176_LCRMASK				854
#define SI32176_LCRMASK_POLREV		855
#define SI32176_LCRMASK_STATE		856
#define SI32176_LCRMASK_LINECAP		857
#define SI32176_LONGHITH			858
#define SI32176_LONGLOTH			859
#define SI32176_IRING_LIM			860
#define SI32176_AC_ADC_GAIN			880
#define SI32176_VOV_RING_GND		896
#define SI32176_RXACGAIN_SAVE		906
#define SI32176_DCDC_VREF_MIN		919
#define SI32176_DCDC_VREF_MIN_RNG	920
#define SI32176_DCDC_FSW_NORM		921
#define SI32176_DCDC_FSW_NORM_LO	922
#define SI32176_DCDC_FSW_RING		923
#define SI32176_DCDC_FSW_RING_LO	924
#define SI32176_DCDC_DIN_LIM		925
#define SI32176_DCDC_VOUT_LIM		926
#define SI32176_SCALE_KAUDIO		967
#define SI32176_DCDC_DCFF_ENABLE	1522
#define SI32176_PD_DCDC				1538
#define SI32176_DCDC_UVHYST			1545
#define SI32176_DCDC_UVTHRESH		1546
#define SI32176_DCDC_OVTHRESH		1547
#define SI32176_DCDC_OITHRESH		1548
#define SI32176_DCDC_STATUS			1551
#define SI32176_DCDC_SWDRV_POL		1553
#define SI32176_DCDC_SWFET			1555
#define SI32176_DCDC_VREF_CTRL		1558
#define SI32176_DCDC_RNGTYPE		1560
#define SI32176_DCDC_ANA_GAIN		1585
#define SI32176_DCDC_ANA_TOFF		1586
#define SI32176_DCDC_ANA_TONMIN		1587
#define SI32176_DCDC_ANA_TONMAX		1588
#define SI32176_DCDC_ANA_DSHIFT		1589
#define SI32176_DCDC_ANA_LPOLY		1590

#endif // NB6

#endif
