ifneq ($(findstring release,$(MAKECMDGOALS)),)
export RELEASE_BUILD=1
endif

ifneq ($(OPERATOR),)
UOPERATOR	:= $(strip $(call upper,$(OPERATOR)))
endif

RELEASE			 = 3.1.10
CONFIG_VERSION		 = 97.0

GENERIC_FIRMWARE	 = $(UBOX)-$(UPROFILE)-$(if $(UOPERATOR),$(UOPERATOR)-)R$(RELEASE)
GENERIC_MAIN_FIRMWARE	 = $(UBOX)-MAIN-$(if $(UOPERATOR),$(UOPERATOR)-)R$(RELEASE)
GENERIC_RESCUE_FIRMWARE	 = $(UBOX)-RESCUE-$(if $(UOPERATOR),$(UOPERATOR)-)R$(RELEASE)
#--
GENERIC_IMAGE		 = $(UBOX)-IMAGE-$(if $(UOPERATOR),$(UOPERATOR)-)$($(UBOX)_BOOTLOADER)_$($(UBOX)_MAIN_FIRMWARE)_$($(UBOX)_RESCUE_FIRMWARE)
#--
GENERIC_CONFIG_VERSION	 = $(UBOX)-CONFIG-$(if $(UOPERATOR),$(UOPERATOR)-)R$(CONFIG_VERSION)
GENERIC_SEED_VERSION	 = $(UBOX)-SEED-$(if $(UOPERATOR),$(UOPERATOR)-)R$(RELEASE)
