
X86_IPADDR		 = localhost

X86_BOOTLOADER		 = $(UBOX)-BOOTLOADER-R0.0.1
X86_MAIN_FIRMWARE	 = $(GENERIC_FIRMWARE)
X86_RESCUE_FIRMWARE      = $(GENERIC_FIRMWARE)
X86_ADSL_FIRMWARE	 = $(UBOX)-ADSL-R0
#--
X86_IMAGE		 = $(GENERIC_IMAGE)_$(X86_ADSL_FIRMWARE)
#--
X86_CONFIG_VERSION	 = $(GENERIC_CONFIG_VERSION)

#---------------------------------------------------------
X86_MAIN_MAX_SIZE	= 12582912
X86_RESCUE_MAX_SIZE	= 2621440

define Efixo/x86/Install
endef

$(TFTPBOOT_DIR)/$(X86_BOOTLOADER):
$(TFTPBOOT_DIR)/$(X86_ADSL_FIRMWARE):
$(TFTPBOOT_DIR)/$(X86_IMAGE):
